apiVersion: v2
publisher: haskell
name: vscode-haskell
version: 1.1.0
type: VS Code extension
displayName: Haskell
title: Haskell language support
description: This extension adds rich language support for the Haskell syntax
icon: https://github.com/haskell/vscode-haskell/blob/master/images/haskell-logo.png
repository: https://github.com/haskell/vscode-haskell
category: Language
firstPublicationDate: '2020-08-26'
spec:
  containers:
    - image: "quay.io/gattytto/che-sidecar-haskell:latest"
      name: vscode-haskell
      memoryLimit: 2Gi
      volumes:
      - mountPath: "/home/theia/home/theia"
        name: vscode-theia-workaround
  extensions:
    - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/justusadam/vsextensions/language-haskell/3.3.0/vspackage
    - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/haskell/vsextensions/haskell/1.1.0/vspackage
