apiVersion: v2
publisher: gattytto
name: plantuml
version: 2.13.13
type: VS Code extension
displayName: PlantUML
title: PlantUML support
description: This extension adds support for the PlantUML Server
icon: https://github.com/gattytto/vscode-plantuml/raw/master/images/icon.png
repository: https://github.com/gattytto/vscode-plantuml
category: Language
firstPublicationDate: '2020-09-22'
spec:
  containers:
    - image: "quay.io/eclipse/che-sidecar-plantuml:2.13.13-ee2987c"
      name: vscode-plantuml
      memoryLimit: '512Mi'
      volumes:
        - mountPath: "/tmp/vscode-unpacked"
          name: "previewassets"
  extensions:
    - https://open-vsx.org/api/jebbs/plantuml/2.13.12/file/jebbs.plantuml-2.13.12.vsix
