apiVersion: v2
publisher: ms-vscode
name: tekton
version: 0.0.3
type: VS Code extension
displayName: Tekton
title: Tekton pipelines support
description: This extension adds rich pipeline support for Tekton
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/redhat-developer/vscode-tekton
category: Language
firstPublicationDate: '2019-09-19'
spec:
  containers:
    - image: "quay.io/che-sidecar-tekton:latest"
      name: vscode-tekton
      memoryLimit: '384Mi'
      volumes:
      - mountPath: "/home/theia/.kube"
        name: kube
  extensions:
    - https://github.com/redhat-developer/vscode-yaml/releases/download/0.15.0/redhat.vscode-yaml-0.15.0.vsix
    - https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-kubernetes-tools/vscode-kubernetes-tools-1.2.1.vsix
    - https://open-vsx.org/api/redhat/vscode-tekton-pipelines/0.11.1/file/redhat.vscode-tekton-pipelines-0.11.1.vsix
    
