apiVersion: v2
publisher: Dart-Code
name: dart-code
version: 3.13.2
type: VS Code extension
displayName: Dart
title: Google's Dart language support
description: This extension adds rich language support for the Dart syntax
icon: https://github.com/zxh0/vscode-proto3/raw/master/images/vscode_extension_icon.png
repository: https://github.com/Dart-Code/Dart-Code
category: Language
firstPublicationDate: '2020-08-26'
spec:
  containers:
    - image: "quay.io/gattytto/che-sidecar-dart:latest"
      name: vscode-dart
      memoryLimit: '256Mi'
  extensions:
    - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/Dart-Code/vsextensions/dart-code/3.13.2/vspackage
