apiVersion: v2
publisher: ms-vscode
name: vetur
version: 0.22.6
type: VS Code extension
displayName: Vetur
title: Rich Vue.js support
description: Vue tooling for VS Code
icon: https://upload.wikimedia.org/wikipedia/commons/9/95/Vue.js_Logo_2.svg
repository: https://github.com/vuejs/vetur.git
category: Language
firstPublicationDate: "2019-07-02"
spec:
  containers:
    - image: 'quay.io/eclipse/che-sidecar-node:10-0cb5d78'
      name: vetur
      memoryLimit: '512Mi'
  extensions:
    - https://github.com/vuejs/vetur/releases/download/v0.26.1/vetur-0.26.1.vsix
