apiVersion: v2
publisher: ms-vscode
name: gogrpc
version: 0.11.4
type: VS Code extension
displayName: Go-GRPC
title: Rich Go language support
description: This extension adds rich language support for the Go language
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/Microsoft/vscode-go.git
category: Language
firstPublicationDate: '2019-09-19'
spec:
  containers:
    - image: "quay.io/gattytto/che-sidecar-go_grpc:latest"
      name: vscode-go
      memoryLimit: '512Mi'
      env:
      - name: GOPATH
        value: /go:$(CHE_PROJECTS_ROOT)
  extensions:
    - https://github.com/microsoft/vscode-go/releases/download/0.14.3/Go-0.14.3.vsix
