apiVersion: v2
publisher: ms-vscode
name: gogrpc
version: crio
type: VS Code extension
displayName: Go-CRI-O
title: Rich Go language support
description: This extension adds rich language support for the Go with crio includes sources
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/Microsoft/vscode-go.git
category: Language
firstPublicationDate: '2019-09-19'
spec:
  containers:
    - image: "quay.io/gattytto/che-sidecar-go:latest"
      name: vscode-go
      memoryLimit: '1500Mi'
  extensions:
    - https://open-vsx.org/api/gattytto/go/0.23.9-dev/file/gattytto.go-0.23.9-dev.vsix
