apiVersion: v2
publisher: ms-vscode
name: scala
version: 1.7.7
type: VS Code extension
displayName: Scala (Metals)
title: Scala language server with rich IDE features
description: This plug-in provides support for Scala development via the Metals language server.
icon: https://rawcdn.githack.com/OlegIlyenko/scala-icon/c453c6f67dfcc1dbf0ca1e437d32d04f1d710983/scala-icon.svg
repository: https://github.com/scalameta/metals-vscode
category: Language
firstPublicationDate: "2020-02-04"
spec:
  containers:
    - image: "quay.io/gattytto/che-sidecar-scala:latest"
      name: vscode-metals
      memoryLimit: "1500Mi"
  extensions:
    - https://github.com/scalameta/metals-vscode/releases/download/v1.7.7/scalameta.metals-1.7.7.vsix
